# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a565b3af383737417cf745e085fa1a59c086d0799f26f3a4eeadef0ef524d7f0435cd9e8203726e241b07ae0729ee1ed5b0a472403669ac4c1817211d3b93fb

test:
  secret_key_base: 8f5c38a8c822ed69e35fd67d6eb3d4187a32014a1ac402e54be52f6de5f68a1c26ff6f95de4dce7ee7d63a0e70771005cd1366c02f86fc21cc377a08202c51ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
